// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Favorite struct {
	ID          int64     `json:"id"`
	FromStation int64     `json:"from_station"`
	ToStation   int64     `json:"to_station"`
	Label       string    `json:"label"`
	CreatedAt   time.Time `json:"created_at"`
}

type Schedule struct {
	ID        int64  `json:"id"`
	TrainID   int64  `json:"train_id"`
	StationID int64  `json:"station_id"`
	Arrival   string `json:"arrival"`
	Departure string `json:"departure"`
	Sequence  int64  `json:"sequence"`
}

type Search struct {
	ID          int64     `json:"id"`
	FromStation int64     `json:"from_station"`
	ToStation   int64     `json:"to_station"`
	CreatedAt   time.Time `json:"created_at"`
}

type Station struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
	Line string `json:"line"`
}

type Train struct {
	ID          int64  `json:"id"`
	TrainNumber string `json:"train_number"`
	RouteName   string `json:"route_name"`
}
