// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package sqlc

import (
	"context"
)

const searchDepartures = `-- name: SearchDepartures :many
SELECT t.id, t.train_number, t.route_name, origin.departure AS departure,
       destination.arrival AS arrival
FROM schedules origin
JOIN schedules destination ON destination.train_id = origin.train_id
JOIN trains t ON t.id = origin.train_id
WHERE origin.station_id = ? AND destination.station_id = ?
  AND origin.sequence < destination.sequence
ORDER BY origin.departure
`

type SearchDeparturesParams struct {
	StationID   int64 `json:"station_id"`
	StationID_2 int64 `json:"station_id_2"`
}

type SearchDeparturesRow struct {
	ID          int64  `json:"id"`
	TrainNumber string `json:"train_number"`
	RouteName   string `json:"route_name"`
	Departure   string `json:"departure"`
	Arrival     string `json:"arrival"`
}

func (q *Queries) SearchDepartures(ctx context.Context, arg SearchDeparturesParams) ([]SearchDeparturesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDepartures, arg.StationID, arg.StationID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDeparturesRow
	for rows.Next() {
		var i SearchDeparturesRow
		if err := rows.Scan(
			&i.ID,
			&i.TrainNumber,
			&i.RouteName,
			&i.Departure,
			&i.Arrival,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
