// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stations.sql

package sqlc

import (
	"context"
)

const getStationByID = `-- name: GetStationByID :one
SELECT id, code, name, line FROM stations WHERE id = ?
`

func (q *Queries) GetStationByID(ctx context.Context, id int64) (Station, error) {
	row := q.db.QueryRowContext(ctx, getStationByID, id)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Line,
	)
	return i, err
}

const listStations = `-- name: ListStations :many
SELECT id, code, name, line FROM stations ORDER BY name
`

func (q *Queries) ListStations(ctx context.Context) ([]Station, error) {
	rows, err := q.db.QueryContext(ctx, listStations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Station
	for rows.Next() {
		var i Station
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Line,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
